import { TapItem, Achievement } from '@/types';

export const INITIAL_ITEMS: TapItem[] = [
  // ===== 传统乐器（免费）=====
  {
    id: 'wooden_fish',
    name: '木鱼',
    description: '经典功德声，敲击积累功德',
    category: 'traditional',
    soundFile: 'wooden_fish.mp3',
    imageEmoji: '🐟',
    iconName: 'musical-note',
    iconColor: '#8B4513',
    vibrationPattern: [{"style":"rigid","delay":0}],
    interactionMode: "tapOrHold",
    holdDuration: 400,
    holdHaptics: [{"style":"medium","delay":0},{"style":"medium","delay":120}],
    releaseHaptics: [],
    isPremium: false,
    isUnlocked: true,
  },
  {
    id: 'gong',
    name: '铜锣',
    description: '悠长回响，声震四方',
    category: 'traditional',
    soundFile: 'gong.mp3',
    imageEmoji: '🥁',
    iconName: 'disc',
    iconColor: '#B8860B',
    vibrationPattern: [{"style":"heavy","delay":0},{"style":"heavy","delay":45},{"style":"medium","delay":110},{"style":"soft","delay":190},{"style":"soft","delay":280},{"style":"light","delay":380}],
    interactionMode: "tap",
    holdDuration: 0,
    holdHaptics: [],
    releaseHaptics: [],
    isPremium: false,
    isUnlocked: true,
  },
  {
    id: 'drum',
    name: '小鼓',
    description: '轻快节奏，敲击律动',
    category: 'traditional',
    soundFile: 'drum.mp3',
    imageEmoji: '🥁',
    iconName: 'radio',
    iconColor: '#CD853F',
    vibrationPattern: [{"style":"medium","delay":0},{"style":"light","delay":50}],
    interactionMode: "tapOrHold",
    holdDuration: 300,
    holdHaptics: [{"style":"light","delay":0},{"style":"light","delay":80}],
    releaseHaptics: [{"style":"medium","delay":0}],
    isPremium: false,
    isUnlocked: true,
  },

  // ===== 现代乐器（付费）=====
  {
    id: 'jazz_drum',
    name: '爵士鼓',
    description: '低沉有力，专业级音效',
    category: 'modern',
    soundFile: 'jazz_drum.mp3',
    imageEmoji: '🥁',
    iconName: 'musical-notes',
    iconColor: '#2F4F4F',
    vibrationPattern: [{"style":"heavy","delay":0},{"style":"heavy","delay":60},{"style":"medium","delay":130},{"style":"light","delay":200}],
    interactionMode: "tap",
    holdDuration: 0,
    holdHaptics: [],
    releaseHaptics: [],
    isPremium: true,
    price: 1.99,
    isUnlocked: false,
  },
  {
    id: 'triangle',
    name: '三角铁',
    description: '清脆叮声，悦耳动听',
    category: 'modern',
    soundFile: 'triangle.mp3',
    imageEmoji: '🔺',
    iconName: 'triangle',
    iconColor: '#C0C0C0',
    vibrationPattern: [{"style":"light","delay":0},{"style":"light","delay":30},{"style":"light","delay":60}],
    interactionMode: "tapOrHold",
    holdDuration: 500,
    holdHaptics: [{"style":"light","delay":0},{"style":"light","delay":40},{"style":"light","delay":80}],
    releaseHaptics: [],
    isPremium: true,
    price: 0.99,
    isUnlocked: false,
  },

  // ===== 办公用品（免费 + 付费）=====
  {
    id: 'mechanical_keyboard',
    name: '机械键盘',
    description: '青轴咔嗒声，办公必备',
    category: 'modern',
    soundFile: 'keyboard.mp3',
    imageEmoji: '⌨️',
    iconName: 'keypad',
    iconColor: '#4A4A4A',
    vibrationPattern: [{"style":"medium","delay":0},{"style":"rigid","delay":25}],
    interactionMode: "tapOrHold",
    holdDuration: 0,
    holdHaptics: [{"style":"light","delay":0},{"style":"light","delay":60}],
    releaseHaptics: [],
    isPremium: false,
    isUnlocked: true,
  },
  {
    id: 'mouse_click',
    name: '鼠标点击',
    description: '清脆点击，简洁高效',
    category: 'modern',
    soundFile: 'mouse.mp3',
    imageEmoji: '🖱️',
    iconName: 'hand-left',
    iconColor: '#708090',
    vibrationPattern: [{"style":"light","delay":0}],
    interactionMode: "tap",
    holdDuration: 0,
    holdHaptics: [],
    releaseHaptics: [],
    isPremium: false,
    isUnlocked: true,
  },
  {
    id: 'stapler',
    name: '订书机',
    description: '咔嚓一声，整理文件',
    category: 'modern',
    soundFile: 'stapler.mp3',
    imageEmoji: '📎',
    iconName: 'clipboard',
    iconColor: '#696969',
    vibrationPattern: [{"style":"heavy","delay":0},{"style":"rigid","delay":15}],
    interactionMode: "swipe",
    holdDuration: 500,
    holdHaptics: [{"style":"soft","delay":0},{"style":"soft","delay":80},{"style":"soft","delay":160},{"style":"soft","delay":240},{"style":"medium","delay":350}],
    releaseHaptics: [{"style":"heavy","delay":0},{"style":"rigid","delay":15}],
    isPremium: true,
    price: 0.99,
    isUnlocked: false,
  },
  {
    id: 'spacebar',
    name: '空格键',
    description: '厚实砰声，解压神器',
    category: 'modern',
    soundFile: 'spacebar.mp3',
    imageEmoji: '␣',
    iconName: 'tablet-landscape',
    iconColor: '#2C3E50',
    vibrationPattern: [{"style":"heavy","delay":0}],
    interactionMode: "holdRelease",
    holdDuration: 300,
    holdHaptics: [{"style":"medium","delay":0},{"style":"medium","delay":100}],
    releaseHaptics: [{"style":"heavy","delay":0}],
    isPremium: true,
    price: 1.49,
    isUnlocked: false,
  },

  // ===== 趣味物品（免费 + 付费）=====
  {
    id: 'cat_head',
    name: '猫头',
    description: '喵一声，萌化人心',
    category: 'fun',
    soundFile: 'cat.mp3',
    imageEmoji: '🐱',
    iconName: 'paw',
    iconColor: '#FF8C69',
    vibrationPattern: [{"style":"soft","delay":0}],
    interactionMode: "holdRelease",
    holdDuration: 400,
    holdHaptics: [{"style":"soft","delay":0},{"style":"soft","delay":60},{"style":"soft","delay":120}],
    releaseHaptics: [{"style":"soft","delay":0}],
    isPremium: false,
    isUnlocked: true,
  },
  {
    id: 'watermelon',
    name: '西瓜',
    description: '砰砰声，夏日清凉',
    category: 'fun',
    soundFile: 'watermelon.mp3',
    imageEmoji: '🍉',
    iconName: 'nutrition',
    iconColor: '#4CAF50',
    vibrationPattern: [{"style":"heavy","delay":0},{"style":"medium","delay":80}],
    interactionMode: "tapOrHold",
    holdDuration: 400,
    holdHaptics: [{"style":"medium","delay":0},{"style":"light","delay":100}],
    releaseHaptics: [],
    isPremium: true,
    price: 1.99,
    isUnlocked: false,
  },
  {
    id: 'knob',
    name: '旋钮',
    description: '滑动旋转，咔哒解压',
    category: 'fun',
    soundFile: 'knob_click.wav',
    imageEmoji: '🔴',
    iconName: 'sync',
    iconColor: '#FF9800',
    vibrationPattern: [{"style":"light","delay":0}],
    interactionMode: "swipe",
    holdDuration: 0,
    holdHaptics: [],
    releaseHaptics: [],
    isPremium: true,
    price: 0.99,
    isUnlocked: false,
  },
  {
    id: 'bubble_wrap',
    name: '泡泡纸',
    description: '捏泡泡声，解压满分',
    category: 'fun',
    soundFile: 'bubble.mp3',
    imageEmoji: '🫧',
    iconName: 'apps',
    iconColor: '#7CB9E8',
    vibrationPattern: [{"style":"light","delay":0},{"style":"light","delay":60},{"style":"light","delay":110},{"style":"light","delay":150}],
    interactionMode: "tap",
    holdDuration: 0,
    holdHaptics: [],
    releaseHaptics: [],
    isPremium: true,
    price: 1.49,
    isUnlocked: false,
  },

  // ===== 成就解锁（隐藏）=====
  {
    id: 'golden_fish',
    name: '金色木鱼',
    description: '敲击 10000 次解锁，功德无量',
    category: 'achievement',
    soundFile: 'golden_fish.mp3',
    imageEmoji: '🐟',
    iconName: 'star',
    iconColor: '#FFD700',
    vibrationPattern: [{"style":"heavy","delay":0},{"style":"heavy","delay":70},{"style":"medium","delay":140}],
    interactionMode: "holdRelease",
    holdDuration: 500,
    holdHaptics: [{"style":"medium","delay":0},{"style":"medium","delay":120},{"style":"medium","delay":240}],
    releaseHaptics: [{"style":"heavy","delay":0},{"style":"heavy","delay":70},{"style":"medium","delay":140}],
    isPremium: false,
    unlockCondition: '累计敲击 10000 次',
    isUnlocked: false,
  },
  {
    id: 'cyber_fish',
    name: '赛博木鱼',
    description: '连续敲击 100 次解锁，未来科技',
    category: 'achievement',
    soundFile: 'cyber_fish.mp3',
    imageEmoji: '🤖',
    iconName: 'hardware-chip',
    iconColor: '#00E5FF',
    vibrationPattern: [{"style":"rigid","delay":0},{"style":"rigid","delay":45},{"style":"light","delay":90},{"style":"light","delay":135}],
    interactionMode: "holdRelease",
    holdDuration: 400,
    holdHaptics: [{"style":"rigid","delay":0},{"style":"light","delay":80},{"style":"rigid","delay":160}],
    releaseHaptics: [{"style":"rigid","delay":0},{"style":"rigid","delay":45},{"style":"light","delay":90}],
    isPremium: false,
    unlockCondition: '连续敲击 100 次',
    isUnlocked: false,
  },
];

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_tap',
    title: '初次敲击',
    description: '第一次敲击物品',
    icon: 'hand-left',
    condition: (progress) => progress.totalTaps >= 1,
    isUnlocked: false,
  },
  {
    id: 'hundred_taps',
    title: '百次敲击',
    description: '累计敲击 100 次',
    icon: 'ribbon',
    condition: (progress) => progress.totalTaps >= 100,
    isUnlocked: false,
  },
  {
    id: 'thousand_taps',
    title: '千次敲击',
    description: '累计敲击 1000 次',
    icon: 'flame',
    condition: (progress) => progress.totalTaps >= 1000,
    isUnlocked: false,
  },
  {
    id: 'ten_thousand_taps',
    title: '万次敲击',
    description: '累计敲击 10000 次',
    icon: 'star',
    condition: (progress) => progress.totalTaps >= 10000,
    reward: 'golden_fish',
    isUnlocked: false,
  },
  {
    id: 'combo_10',
    title: '连击高手',
    description: '连续敲击 10 次',
    icon: 'flash',
    condition: (progress) => progress.currentStreak >= 10,
    isUnlocked: false,
  },
  {
    id: 'combo_50',
    title: '连击大师',
    description: '连续敲击 50 次',
    icon: 'sparkles',
    condition: (progress) => progress.currentStreak >= 50,
    isUnlocked: false,
  },
  {
    id: 'combo_100',
    title: '连击传奇',
    description: '连续敲击 100 次',
    icon: 'diamond',
    condition: (progress) => progress.currentStreak >= 100,
    reward: 'cyber_fish',
    isUnlocked: false,
  },
  {
    id: 'collector',
    title: '收藏家',
    description: '解锁所有物品',
    icon: 'trophy',
    condition: (progress) => progress.unlockedItems.length >= INITIAL_ITEMS.length,
    isUnlocked: false,
  },
  {
    id: 'week_streak',
    title: '持之以恒',
    description: '连续 7 天敲击',
    icon: 'calendar',
    condition: (progress) => progress.currentStreak >= 7,
    isUnlocked: false,
  },
  {
    id: 'night_owl',
    title: '夜猫子',
    description: '凌晨 1-5 点敲击',
    icon: 'moon',
    condition: () => {
      const hour = new Date().getHours();
      return hour >= 1 && hour <= 5;
    },
    isUnlocked: false,
  },
];

export const DEFAULT_PROGRESS = {
  totalTaps: 0,
  todayTaps: 0,
  currentStreak: 0,
  longestStreak: 0,
  unlockedItems: ['wooden_fish', 'gong', 'drum', 'mechanical_keyboard', 'mouse_click', 'cat_head'],
  achievements: [],
  favoriteItem: 'wooden_fish',
  lastTapDate: new Date().toISOString(),
  dailyHistory: {} as Record<string, number>,
};

export const DEFAULT_SETTINGS = {
  language: 'zh-CN',
  soundEnabled: true,
  vibrationEnabled: true,
  vibrationStrength: 100,
  theme: 'zen' as const,
  notificationsEnabled: false,
};

export const THEME_COLORS = {
  zen: {
    primary: '#5D4037',
    secondary: '#B8860B',
    background: '#F5F1E8',
    accent: '#C41E3A',
    text: '#2C2C2C',
    card: '#FFFFFF',
    border: '#D4C5B0',
  },
  cyber: {
    primary: '#8B5CF6',
    secondary: '#06B6D4',
    background: '#0F172A',
    accent: '#EC4899',
    text: '#F8FAFC',
    card: '#1E293B',
    border: '#334155',
  },
};

export const COMBO_INTERVAL = 2000;

export const STORAGE_KEYS = {
  PROGRESS: '@cyber_tap:progress',
  SETTINGS: '@cyber_tap:settings',
  UNLOCKED_ITEMS: '@cyber_tap:unlocked_items',
  ACHIEVEMENTS: '@cyber_tap:achievements',
};
